development:
  adapter: postgresql
  database: TaskProject_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: TaskProject_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: TaskProject_production
  pool: 5
  timeout: 5000
